spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cathaybk?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Taipei
    username: cathaybk
    password: cathaybk
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
